config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users
  root 'pages#home'

  get '/user' => "groups#index", :as => :user_root

  resources :groups do
    resources :operations
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :operations
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true
  after_commit :add_default_image, on: %i[create update]

  def value
    value = 0
    operations&.each do |op|
      value += op.amount
    end
    value
  end

  private

  def add_default_image
    return if image.attached?

    image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'placeholder-image.png')),
                 filename: 'placeholder-image.png', content_type: 'image/png')
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /groups or /groups.json
  def index
    @groups = Group.includes([:user]).where(user_id: current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :image)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: 'p-0 d-flex flex-column gap-2') do |form| %>
    <% if group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
  
        <ul>
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="mt-3 d-flex flex-column gap-2 border border-1">
        <%= form.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Name', class: 'border-0 border-bottom p-2' %>
        <%= form.file_field :image, accept: 'image/png, image/jpeg' %>
    </div>
  
    <div class="bg-second d-flex justify-content-center fixed-bottom">
        <div style="width: 100%;" class="p-2 m-2">
            <%= form.submit 'Submit', class: 'bg-transparent border w-100 py-2 text-white' %>
        </div>
    </div>
  <% end %>
  

app/views/groups/_group.html.erb
<div class='m-2 p-2 border d-flex justify-content-between' id="<%= dom_id group %>">

  <div class='d-flex gap-4 mx-2'>
    <%= image_tag group.image, :style => 'width: 64px; height: 64px; object-fit: cover;' %>
    <div class='text-4 d-flex flex-column justify-content-between'>
      <%= group.name %>
      <br>
      <span class='small'><%= group.created_at.to_date %></span>
    </div>
  </div>


  <div class='m-2 d-flex align-items-center' >
    <strong class='text-center align-middle' ><%= number_to_currency(group.value, precision: 2) %></strong>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class="nav bg-main d-flex justify-content-between align-items-center p-2">
  <%= button_to "< Log out", destroy_user_session_path, method: :delete, class: 'bg-transparent text-white m-0 border-0 text-decoration-none' %>
  <h5 class='text-white m-0 py-2'>CATEGORIES</h5>
  <%= link_to 'Home', '/user', class: "text-white m-0 border-0 text-decoration-none px-2" %>
</div>

<div class="container p-0">
  <div id="groups" class="mb-5 pb-5">
    <% @groups.each do |group| %>
      <%= link_to(group_operations_path(group), class: "text-decoration-none link-dark") do%>
        <%= render group %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="bg-second d-flex justify-content-center fixed-bottom">
  <div style="width: 100%;" class="p-2 m-2">
    <%= button_to "NEW CATEGORY", new_group_path, method: :get, class: 'bg-transparent border w-100 py-2 text-white' %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="nav bg-main d-flex justify-content-between align-items-center p-2">
  <%= link_to '< Back', '/user', class: "text-white m-0 border-0 text-decoration-none px-2" %>
  <h5 class='text-white m-0 py-2'>NEW CATEGORY</h5>
  <%= link_to 'Home', '/user', class: "text-white m-0 border-0 text-decoration-none px-2" %>
</div>

<%= render "form", group: @group %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>
  <%= button_to "Destroy this group", @group, method: :delete %>
</div>