config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users
  root 'pages#home'

  get '/user' => "groups#index", :as => :user_root

  resources :groups do
    resources :operations
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :author, presence: true
  validates :amount, presence: true
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /operations or /operations.json
  def index
    @group = Group.find(params[:group_id])
    @operations = @group.operations.order(created_at: :desc)
  end

  # GET /operations/1 or /operations/1.json
  def show; end

  # GET /operations/new
  def new
    @group = Group.find(params[:group_id])
    user = @group.user
    @operation = Operation.new
    @categories = Group.where(user_id: user.id).order(name: :desc)
  end

  # GET /operations/1/edit
  def edit; end

  # POST /operations or /operations.json
  def create
    @group = Group.find(params[:group_id])
    @operation = Operation.new(operation_params)
    @operation.author = current_user.name
    @operation.user = current_user
    if params[:operation][:categories].nil?
      @operation.groups.push(@group) unless @operation.groups.include?(@group)
    else
      params[:operation][:categories].each do |id|
        @operation.groups.push(Group.find(id)) unless @operation.groups.include?(Group.find(id))
      end
    end
    respond_to do |format|
      if @operation.save
        format.html { redirect_to group_operations_url(@group), notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_operation
    @operation = Operation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def operation_params
    params.require(:operation).permit(:author, :references, :name, :amount)
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_with model: operation, url: group_operations_path, method: :post do |form| %>
    <% if operation.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>
  
        <ul>
          <% operation.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="mt-3 d-flex flex-column gap-2 border border-1">
        <%= form.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Operation name', class: 'border-0 border-bottom p-2' %>
        <%= form.number_field :amount, autofocus: true, placeholder: 'Operation amount', class: 'border-0 border-bottom p-2' %>
        <div class="d-flex gap-5 flex-wrap px-3">
          <% @categories.each do |cat| %>
            <div>
              <%= form.check_box :categories,{ multiple: true }, cat.id, nil %>
              <%= form.label cat.name %>
            </div>
          <% end %>
        </div>
        
    </div>
  
    <div class="bg-second d-flex justify-content-center fixed-bottom">
      <div style="width: 100%;" class="p-2 m-2">
        <%= form.submit 'Submit', class: 'bg-transparent border w-100 py-2 text-white' %>
      </div>
    </div>
  <% end %>
  

app/views/operations/_operation.html.erb
<div class='m-2 p-2 border d-flex justify-content-between' id="<%= dom_id operation %>">
  <div class='d-flex gap-4 mx-2'>  
    <div class='d-flex flex-column justify-content-between'>
      <strong><%= operation.name %></strong>
      <span class='small'><%= operation.author %></span>
      <span class='small'><%= operation.created_at.to_date %></span>
    </div>
  </div>

  <div class='m-2 d-flex align-items-center' >
    <strong class='text-center align-middle' ><%= number_to_currency(operation.amount, precision: 2) %></strong>
  </div>
</div>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @operation %> |
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/index.html.erb
<div class="nav bg-main d-flex justify-content-between align-items-center p-2">
  <%= link_to '< Back', '/user', class: "text-white m-0 border-0 text-decoration-none px-2" %>
  <h5 class='text-white m-0 py-2'><%= @group.name %></h5>
  <%= link_to 'Home', '/user', class: "text-white m-0 border-0 text-decoration-none px-2" %>
</div>

<h1 class="bg-second text-center">Total: <%= number_to_currency(@group.value, precision: 2) %></h1>

<div id="operations" class="mb-5 pb-5">
  <% @operations.each do |operation| %>
    <%= render operation %>
  <% end %>
</div>

<div class="bg-second d-flex justify-content-center fixed-bottom">
  <div style="width: 100%;" class="p-2 m-2">
    <%= button_to "NEW OPERATION", new_group_operation_path(@group), method: :get, class: 'bg-transparent border w-100 py-2 text-white' %>
  </div>
</div>

app/views/operations/new.html.erb
<div class="nav bg-main d-flex justify-content-between align-items-center p-2">
  <%= link_to '< Back', group_operations_path(@group), class: "text-white m-0 border-0 text-decoration-none px-2" %>
  <h5 class='text-white m-0 py-2'>NEW OPERATION</h5>
  <%= link_to 'Home', '/user', class: "text-white m-0 border-0 text-decoration-none px-2" %>
</div>

<%= render "form", operation: @operation %>

app/views/operations/show.html.erb
<%= render @operation %>

<div>
  <%= link_to "Edit this operation", edit_operation_path(@operation) %> |
  <%= link_to "Back to operations", operations_path %>

  <%= button_to "Destroy this operation", @operation, method: :delete %>
</div>